name: once was instagram
favicon: null
layout_spectrum: 0.83149
typography_spectrum: 0.1502384808845818
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.125
  lightness: 0.4846001185942441
  saturation: 0.37969302712008357
  rhythmicContrast: 0.843922937521711
purpose: []
